### ISSUE TITLE
Can you add apps and change input name?

### ISSUE THREAD

**Issue by LavlavOP** [o-lukas/homebridge-smartthings-tv#1]
works good, is there an option to add apps(Netflix,YouTube). 
Thanks

**Comment by o-lukas** [comment]
Currently there is no option to open apps.

Unfortunately the SmartThings API seems to offer no calls to:

- get installed apps of TV
- check if an app is running

There seems to be a way to open an app but I have no clue how to determine if the app is really running and therefore show the correct input state.
