### ISSUE TITLE
Apple home forgets switch and input names after restarting Homebridge

### ISSUE THREAD

**Issue by simonheng** [o-lukas/homebridge-smartthings-tv#107]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

First, let me say thank you for this amazing plugin, I love the functionality this adds to my smart home!

However, I am encountering a small issue: every time I restart the Homebridge, Apple Home forgets the names I set for the sound/picture mode switches, and they are moved from any scenes/automations. Is there any way I can avoid this? 
One suspicion I have is that the plugin tries to name the switch something like "Picture: standard". However, Apple Home does not allow colons in the device names.

Thanks!

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment]
I will try to have a look at it tomorrow. Thanks for the tip regarding the colons. I will check if it solves the issue and will ket you know.

**Comment by simonheng** [comment]
Awesome man! I will give it a try when the new version is online!

**Comment by o-lukas** [comment]
@simonheng: could you please install version 1.4.6-next.3 and verify everything is now working as expected. If it does I will create a proper release.

**Comment by simonheng** [comment]
> @simonheng: could you please install version 1.4.6-next.3 and verify everything is now working as expected. If it does I will create a proper release.

Thanks for the work! I just tried it, but sadly something is still going wrong for me. When I restart the homebridge, the names seem to get reset to the defaults (e.g. “Sound Adaptive”) and the custom name I added gets removed. This is not really such a big issue. However, the switches that I added to a scene or automation also get removed from it. For instance, I created a scene “Movie Time” which switches on the Surround Sound mode. After I restart the homebridge the switch accessory is removed from the scene. It is like all the accessories get removed and readded.

**Comment by o-lukas** [comment]
Thanks for your fast feedback! This seems to be a problem with the accessory caching. I didn't have a look at the caching until now as it didn't seem to be needed so I didn't implement it. But I will try to have a look at it :)

**Comment by o-lukas** [comment]
I've just created [release V1.5.0](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v1.5.0) which should fix the problems with sound/picture modes. I had to publish the switches as own accessories so they aren't anymore "inside" the TV accessory. Otherwise I didn't get the caching running.

But changing names and using switches in schemes did now work for me. I hope it works for you as well. If not let me know!

**Comment by simonheng** [comment]
Thanks! I tried it out and it works perfectly for the switches now. The only thing is that the names of the input types do not seem to be cached. When I restart the TV, all my four sources are reset to “Samsung TV”. Not a big problem, but just letting you know. Thanks again for fixing the switches, I will make some nice scenes and automations with this!On 17 Jun 2023, at 14:49, Lukas ***@***.***> wrote:﻿
I've just created release V1.5.0 which should fix the problems with sound/picture modes. I had to publish the switches as own accessories so they aren't anymore "inside" the TV accessory. Otherwise I didn't get the caching running.
But changing names and using switches in schemes did now work for me. I hope it works for you as well. If not let me know!

**Comment by o-lukas** [comment]
@simonheng I thought I did have the same behaviour as you but after submitting the new issue I just mentioned and then looking back on my phone the input names were back. Custom names seem to be reset but the original names are now back. Does this behave the same with your TV or are the names of the inputs completely lost.

**Comment by simonheng** [comment]
@o-lukas Yes, the same for me: the input names are visible, but it forgets the custom ones. The problem is that my default ones are all named “Samsung TV” so I cannot really distinguish between them!

**Comment by o-lukas** [comment]
> @o-lukas Yes, the same for me: the input names are visible, but it forgets the custom ones. The problem is that my default ones are all named “Samsung TV” so I cannot really distinguish between them!

I had this happen as well a while ago. In the homebridge settings you can `Unpair Bridges / Cameras / TVs / External Accessories`. You could try to remove the TV from there. Remove it from you Home app and re-add it. This solved the problem for me back then.

**Comment by simonheng** [comment]
Yes! Following these steps worked perfectly. Thanks so much for your help!Have a great week!On 19 Jun 2023, at 17:28, Lukas ***@***.***> wrote:﻿

@o-lukas Yes, the same for me: the input names are visible, but it forgets the custom ones. The problem is that my default ones are all named “Samsung TV” so I cannot really distinguish between them!

I had this happen as well a while ago. In the homebridge settings you can Unpair Bridges / Cameras / TVs / External Accessories. You could try to remove the TV from there. Remove it from you Home app and re-add it. This solved the problem for me back then.
