### ISSUE TITLE
Which ports to open in Firewall

### ISSUE THREAD

**Issue by Chris-We** [o-lukas/homebridge-smartthings-tv#233]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

Which Ports are used by the Plugin?
I'm running homebridge via docker on a Synology DiskStation.
When I have the Firewall of the Diskstation activated the HomeApp doesn't get response by the TV.
When I deactivate the Firewall the TV is shown in the correct state and reacts.

Which Ports do I need to open in the Firewall to allow the communication between the HomeApp and the Plugin?

### Environment Information

```markdown
- Plugin Version: v1.9.1
- Homebridge Version: 1.6.1
- Node.js version: v18.13.0
- NPM version: <!-- npm -v -->
- Operating System: Docker
```

**Comment by o-lukas** [comment]
This plugin does not open specific ports for communication. It uses the Smartthings REST API for getting the TV information.
