### ISSUE TITLE
TV turns off but not on.

### ISSUE THREAD

**Issue by mrrust310** [o-lukas/homebridge-smartthings-tv#246]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe the bug

I'm running Smartthings TV plugin on Hoobs.

It works fine when turning off but not when turning on.

I read in a previous post that the solution was to remove the Device ID, which I did to no avail.

It's a Samsung Frame TV, only used in Art Mode. It's on Wifi, since ethernet wire doesn't work because the TV goes to TV mode when turning on wire and smarthings app fails all the time. Samsung stuff.

### To Reproduce

Turn tv on then off

### Expected behavior

Turn TV on and off with Homekit.

### Logs

11/14/2023, 3:56:38 PMSmartThings Tv Bridge starting11/14/2023, 3:56:42 PMSmartThings Tv BridgeLoaded plugin '@o-lukas/homebridge-smartthings-tv'11/14/2023, 3:56:42 PMSmartThings Tv BridgeLoading 1 platforms...11/14/2023, 3:56:42 PMSmartThings Tv BridgeBridge is running on port 51946.11/14/2023, 3:56:43 PMSmartThings Tv Bridgesmartthings-tvAdding new accessory: Samsung The Frame 43 (c377ab8b-4955-5890-fb7c-4aa1edab75fb)11/14/2023, 3:56:43 PMSmartThings Tv Bridgesmartthings-tv[Samsung The Frame 43] Registering capabilities for component main11/14/2023, 3:56:43 PMSmartThings Tv BridgeSamsung The Frame 43 611D is running on port 44855.11/14/2023, 3:56:44 PMSmartThings Tv Bridgesmartthings-tv[Samsung The Frame 43] Registering capability: Switch11/14/2023, 3:56:44 PMSmartThings Tv Bridgesmartthings-tv[Samsung The Frame 43] Registering capability: Audio Volume11/14/2023, 3:56:45 PMSmartThings Tv Bridgesmartthings-tv[Samsung The Frame 43] Registering capability: Audio Mute11/14/2023, 3:56:49 PMSmartThings Tv Bridgesmartthings-tv[Samsung The Frame 43] Not registering capability because registering of applications has been disabled: launchApp11/14/2023, 3:56:51 PMSmartThings Tv Bridgesmartthings-tv[Samsung The Frame 43] Registering capability: Media Input Source11/14/2023, 3:56:51 PMSmartThings Tv Bridgesmartthings-tvWarning[Samsung The Frame 43] Capability Media Input Source might not work as expected because it's status is: proposed11/14/2023, 3:56:52 PMSmartThings Tv Bridgesmartthings-tv[Samsung The Frame 43] Registering input source: TV

### Logs

{
    "platform": "smartthings-tv",
    "token": "b69e53b7-2538-4dce-a725-4b4173b3c9c9",
    "deviceMappings": [
        {
            "macAddress": "d0:c2:4e:1c:8b:de",
            "ipAddress": "192.168.1.18"
        }
    ]
}

### Environment Information

```markdown
- Plugin Version:
- Hoobs Version: 4.3.0
- Node.js version: 16.20.2
- Operating System: Hoobs
```

**Comment by o-lukas** [comment]
You should not remove the device ID as the plugin can not match IP and mac address to your TV if it is not there.

I think the problem ist that WOL doesn't always work properly using WIFI. Have you tried removing the ip address so the plugin sends the wake request over the Smartthings API?

**Comment by mrrust310** [comment]
> You should not remove the device ID as the plugin can not match IP and mac address to your TV if it is not there.
> 
> I think the problem ist that WOL doesn't always work properly using WIFI. Have you tried removing the ip address so the plugin sends the wake request over the Smartthings API?

I added back the device ID.

I switched to Ethernet cable.

Still able to turn off, but not on.

Then I removed the IP address.

No luck. Still able to turn off but not back on.

I explored the TV settings... Power on with mobile and IP remote are enabled.

Any other ideas?

**Comment by o-lukas** [comment]
Mhm I am running out of ideas as well...

Are you able to turn the TV on using the Smartthings app?
