### ISSUE TITLE
Detecting DisplayPort sources on G9 monitor

### ISSUE THREAD

**Issue by Bl4ckfi3lds** [o-lukas/homebridge-smartthings-tv#252]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe the bug

I am openning a new issue on this mater because the old one has been closed automatically, the previous owner did not respond.
I have and odyssey G9 monitor with 2 HDMI inputs and a DisplayPort Input.
So when using the plugin only the two HDMI sources of the monitor are recognized. The Display port input is not proposed.
I am able to switch to the DisplayPort input with the SmartThings app on my phone. (see below) 
![IMG_3856](https://github.com/o-lukas/homebridge-smartthings-tv/assets/48182839/e7d07212-83db-408e-8f33-00731870b983)

### To Reproduce

Try to pair a G9 monitor with the plug-in

### Expected behavior

All the inputs of the monitor should show in HomeKit.

### Logs

[11/22/2023, 3:12:22 PM] [@o-lukas/homebridge-smartthings-tv] [49" Odyssey OLED G9 1] Registering capability: Media Input Source
[11/22/2023, 3:12:22 PM] [@o-lukas/homebridge-smartthings-tv] [49" Odyssey OLED G9 1] Capability Media Input Source might not work as expected because it's status is: proposed
[11/22/2023, 3:12:22 PM] [@o-lukas/homebridge-smartthings-tv] [49" Odyssey OLED G9 1] Registering input source: PC_abby
[11/22/2023, 3:12:22 PM] [@o-lukas/homebridge-smartthings-tv] [49" Odyssey OLED G9 1] Registering input source: PC_portable

### Logs

            "token": "******",
            "capabilityLogging": true,
            "registerApplications": false,
            "_bridge": {
                "username": "******",
                "port": ****
            },
            "platform": "smartthings-tv"
        }

### Environment Information

```markdown
- Plugin Version: 1.9.1
- Homebridge Version: 1.7.0
- Node.js version: 18.17.1
- NPM version: <!-- npm -v -->
- Operating System: Raspbian
```

**Comment by o-lukas** [comment]
Could you please enable Capability logging in the plugin configuration, enable debug mode of your Homebridge instance and attach the log where capabilites are logged. I need to check if the capability used returns all input sources including the display port. 

Maybe we need to use another capability for this TV...

If you don't want to post the full log here, you can send me the log using the email address in my profile.

**Comment by Bl4ckfi3lds** [comment]
Thank you for your answer, I have dig a little on the web and I think this thread could be link to our issue : https://community.smartthings.com/t/samsung-g8-no-displayport-option-in-mediainputsource/271357
Looks like it's a known issue on the samsung API.

I have attach the log, I have clean it to only let your plugin logs. 
[homebridge.log.txt](https://github.com/o-lukas/homebridge-smartthings-tv/files/13453502/homebridge.log.txt)

Regards

**Comment by o-lukas** [comment]
So it seems like the capability I'm using for changing the input source does not return the DisplayPort source as an available input. The thread you have linked describes the problem as well. 

We might be able to change the input source using a string that is not provided by the API but I'm not sure if this works. I will try to provide an option but I might need your help because I don't have access to the mentioned monitor.

**Comment by Bl4ckfi3lds** [comment]
No problem, tell me what you need me to do.

**Comment by o-lukas** [comment]
Glad you got it working 👍 

Thanks for the screenshot of your configuration. I will add a hint to the README for other people having the same problem!
