### ISSUE TITLE
TV Not Adding in Home App. 

### ISSUE THREAD

**Issue by alexescarce** [o-lukas/homebridge-smartthings-tv#314]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

Hello!

I just attempted to add my tv to homebridge via your plugin, however, when i go to manually add the tv in the home app, it shows, and then i tap it, type in the code and then it just spins. i've restarted, i've reinstalled the app, on the newest version of homebridge, still the same issue

Please assist
![IMG_6850](https://github.com/o-lukas/homebridge-smartthings-tv/assets/30999282/b7e21cc8-9aea-4b15-b605-d2d8d522c443)
![IMG_6849](https://github.com/o-lukas/homebridge-smartthings-tv/assets/30999282/dabd5bd8-6b12-4a9c-833c-2bbb90d5733f)
![IMG_6848](https://github.com/o-lukas/homebridge-smartthings-tv/assets/30999282/cd1fa00a-d9e0-469e-a9f2-6d39668653ea)

### Environment Information

```markdown
- Plugin Version: 1.10.3
- Homebridge Version: 1.7.0
- Node.js version: 18.19.1
- NPM version: <!-- npm -v -->
- Operating System: RHEL 9.3
```

**Comment by o-lukas** [comment]
Please try to reset externally published accessories in Homebridge using: `Unpair Bridges / Cameras / TVs / External Accessories` in the Homebridge settings. Pay attention that this can have effects on other plugins as well so use with caution.

If the problem does still exist after doing this please reopen the issue.

**Comment by alexescarce** [comment]
Hello! 

I get the following, even after unpairing the accessory:

[Living Room TV] Capability Media Input Source might not work as expected because it's status is: proposed

**Comment by o-lukas** [comment]
This is just a warning and should have no effect on other functionalities than selecting the current input source.

Does everything work as expected after unpairing?

**Comment by alexescarce** [comment]
Unfortunately no 😔. I am able to see the TV in my Home App but it just spins. I even reset the TV to factory and readded it to SmartThings, and made sure there were no traces in HB but still the same thing

**Comment by caleb39411** [comment]
Hello, I am having the same issue, and have tried resetting the externally published accessories. The TV shows up in the h
Homebridge accessories pane.

### Environment Information

```
- Plugin Version: 2.1.2
- Homebridge Version: 1.8.4
- Node.js version: 20.12.2
- NPM version: 10.5.0
- Operating System: Fedora Linux Server Edition (40)
```
