### ISSUE TITLE
Trying to add a tv in HomeKit; not working so far ..or might just need a PIN?

### ISSUE THREAD

**Issue by stirlo** [o-lukas/homebridge-smartthings-tv#330]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

Using homebridge and HomeKit all latest releases/ 
Trying to add a tv to HomeKit to use it (it’s showing in the web based Homebridge which is promising though ) 

I click add accessories 
It shows in Nearby devices 
(Sammy 65 556C) name
Asks for a setup code ; not sure what is ideal but I’ve tried a few. 0000 seems to nearly work and 0000-0000 gives an instant 
Accessory not Ready to Connect ; even when the tv is powered on and connected to the network 

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/3212918/b674e700-ccd9-48e2-9ada-c6cde77bf3a5)
![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/3212918/308599d1-e4ea-42de-8c23-9ae90692fab5)
![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/3212918/2cab0570-1783-4a6d-931f-7730091ce9b7)
![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/3212918/9d55cf6d-6604-4f2b-939d-8bd3daee8cd3)
![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/3212918/45a4a628-944e-41a1-a673-a88563304b75)

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service --> Raspian
```

**Comment by stirlo** [comment]
![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/3212918/1c477f7d-38ac-48dc-b8dd-49f98bf8e356)
 
 
With 000000 ^ PIN code it looks like it’s going to connect ; takes a while … then displays this error message; so close as it’s showing serial and all other relevant data in HomeBridge I’m sure it’s not too far from working fully ; q60b model and registered in SmartThings ++ I’ve added MAC address as well just for basic on-off without more 

![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/3212918/99a9b5c7-d349-42c9-b6c3-9211673bebc8)

**Comment by o-lukas** [comment]
You need to use the pin of your Homebridge instance. It should be shown underneath the QR Code of your Homebridge instance

**Comment by stirlo** [comment]
Thanks I’ll try that pin now and see if it works Ok it’s made it into HomeKit ; cheers! :-) Now to sort some unrelated likely DNS stuff that is preventing full use and im all goodthanks and i think this ticket can be closed fully :)On 31 Mar 2024, at 11:32 PM, Lukas ***@***.***> wrote:﻿
You need to use the pin of your Homebridge instance. It should be shown underneath the QR Code of your Homebridge instance
