### ISSUE TITLE
Rename device in Homekit

### ISSUE THREAD

**Issue by jonbisch** [o-lukas/homebridge-smartthings-tv#367]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

When I rename the device in Homekit it changes back to the default name is Homebridge is restarted. Is there a way to force Homekit to use a different device name? It appears to always default back to Configured Name.

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/o-lukas/homebridge-smartthings-tv/assets/8883409/976039a3-21e0-4b14-9024-0e354e305ff2)

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment]
Sorry for late response: does the Homebridge UI show the name correct after restarting? So problem is only in HomeKit?

**Comment by jonbisch** [comment]
Thanks for the reply. Homebridge keeps the correct value in the Name field when I rename it even after restarting, but what I see in HomeKit is the Configured Name value from Homebridge not Name. I've also tried clearing cached devices then re-adding it just to be sure.

The only way I can find to change the name that displays in HomeKit is to change it directly in HomeKit, but it reverts back the Configured Name value when Homebridge is restarted and Configured Name can't be changed.

**Comment by o-lukas** [comment]
This might be the case because the TVs are published as external accessory. So they can not be cached as normal accessory would get in HomeBridge. 

I will try to add an option to change the configured name of a TV in the config file, so you can change it there and it will not get lost.

**Comment by o-lukas** [comment]
I've created a [new release](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v2.1.0). Please check new config property [nameOverride](https://github.com/o-lukas/homebridge-smartthings-tv?tab=readme-ov-file#nameOverride)

**Comment by jonbisch** [comment]
Looks like that did the trick, Thank you so much!
