### ISSUE TITLE
Swap info button in remote app to control source

### ISSUE THREAD

**Issue by kylewhirl** [o-lukas/homebridge-smartthings-tv#368]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I’d like to be able to change inputs with the remote app using the info button. It currently opens the settings menu

### Describe the solution you'd like

Add an option in config to swap info button to open sources instead of settings 

### Describe alternatives you've considered

Samsung Tizen homebridge plugin 

### Additional context

None

**Comment by o-lukas** [comment]
Sorry for late response: sounds like a good idea. I will try to implement it as soon as I can find some time to do it.

**Comment by o-lukas** [comment]
I've created a [new release](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v2.1.0). Please check new config property [infoKey](https://github.com/o-lukas/homebridge-smartthings-tv?tab=readme-ov-file#infokey)
