### ISSUE TITLE
add the TV manually to HomeKit 

### ISSUE THREAD

**Issue by flipdiggity** [o-lukas/homebridge-smartthings-tv#371]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

I can see the Frame TV (Screen and Volume) in the Homebridge Accessories tab, but it never shows up in HomeKit. The instructions say to "add the TV manually to HomeKit" but I'm not entirely sure how to do that. The bridge inside of HomeKit has 0 accessories listed for me to add. 

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment]
The plugin exposes the TV as external accessory which is on the same "layer" as the Bridge itself. So you have to register it by adding manually adding the accessory using the same procedure like adding the bridge itself.

Hope this helps. If you still are not able to add the TV please attach your logs so I can check if everything is running correctly.
