### ISSUE TITLE
Devices not show in homekit

### ISSUE THREAD

**Issue by szarkes** [o-lukas/homebridge-smartthings-tv#38]
Hello, so i install plugin on my homebridge v 1.6.0.  Map devices correct with api and mapping and all my devices show and working on homebridge accesory tab but it didnt show on my homekit, the bridge shows no devices, try without bridge, try with register aplications and capability logging but nothing work, is this bug or i do something wrong

thats how my config looks like 

            "token": "---",
            "capabilityLogging": false,
            "registerApplications": false,
            "deviceMappings": [
                {
                    "deviceId": "Samsung 5 Series (32)",
                    "macAddress": "----",
                    "ipAddress": "192.168.31.102 "
                },
                {
                    "deviceId": "Samsung Q80AA 65 TV",
                    "macAddress": "----",
                    "ipAddress": "192.168.31.109"
                }
            ],
            "platform": "smartthings-tv",
            "_bridge": {
                "username": "----",
                "port": 52522

**Comment by o-lukas** [comment]
Hey there, the device ID should be a GUID so something like this: d73d89d1-5bd6-4765-a1d9-b6870caab466. Please try to use the correct ones and try again. If problem still occurs please attach some log-files so I can check them for something strange. It would be the best if you could increase the log level to debug so the log files show some more data when attaching them.

**Comment by o-lukas** [comment]
Have you added the devices manually after homebridge has started? TVs are a bit special so the must be added manually. You can see a hint about this in your attached log.
