### ISSUE TITLE
audioVolume is cached

### ISSUE THREAD

**Issue by k3mot** [o-lukas/homebridge-smartthings-tv#383]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

I think I screwed something up with the smarthings api. I changed the interval of polling for the volume to something pretty low, I saw the plugin gets errors from samsung's API for too many requests, then I changed it back to every 6000ms and yet, the API always return that the audioVolume of my TV is 7%. I know it's not a cache of the plugin itself, because I tried querying for the volume myself using smarthings core sdk and got 7%. I tried replacing the token to a new one, nothing works. Any idea?

Thanks!

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment]
I did have some trouble with the volume of the TV too but it magically solved itself. The API sometimes seems to be a bit buggy. You might try to remove your TV from SmartThings account and re-add it again. But other than that I sadly have no idea how to solve this problem. Sorry I can not really help...

**Comment by k3mot** [comment]
It actually worked! Thanks!
