### ISSUE TITLE
Soundbar

### ISSUE THREAD

**Issue by jasmas** [o-lukas/homebridge-smartthings-tv#384]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Looking to control Samsung soundbar. Tv is LG. 

### Describe the solution you'd like

Soundbar audio modes / volume control / treble / bass / modes such as night mode, etc

### Describe alternatives you've considered

Currently use the SmartThings app

### Additional context

I tried adding the plugin, but it doesn't seem to see the soundbar

**Comment by o-lukas** [comment]
Soundbars are currently not implemented. I will have a look at it how complicated an implementation would be. I might need your help because I do not have a soundbar myself. So maybe you might need to copy some logs so I can see what the API returns. But first I will have a look at the documentation and see how far I come

**Comment by GreyAsteroid** [comment]
> Soundbars are currently not implemented. I will have a look at it how complicated an implementation would be. I might need your help because I do not have a soundbar myself. So maybe you might need to copy some logs so I can see what the API returns. But first I will have a look at the documentation and see how far I come

I'm currently using a SmartThings soundbar (Q70T) and just wanted to let you know I can provide any information needed to help the cause.

**Comment by o-lukas** [comment]
Hey guys. Sorry for late response - was quite busy the last weeks. Maybe I can find some time the next days. Is it possible one of you could send me an API token with the added SoundBar so I can use it for developing. I will not change anything or trigger any actions but just need to look what the API looks like. Otherwise it would be quite difficult to develop against a blackbox. Please don't post the token here but send it at the email address in my profile.

**Comment by GreyAsteroid** [comment]
> Hey guys. Sorry for late response - was quite busy the last weeks. Maybe I can find some time the next days. Is it possible one of you could send me an API token with the added SoundBar so I can use it for developing. I will not change anything or trigger any actions but just need to look what the API looks like. Otherwise it would be quite difficult to develop against a blackbox. Please don't post the token here but send it at the email address in my profile.

Email sent, let me know if you end up needing anything else.

**Comment by o-lukas** [comment]
Thanks @GreyAsteroid for providing your API token. I was able to implement some basic commands. But I was not really able to test them as I did not want to change anything on your device. 

I have created a [pre-release version](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v2.2.0-next.1) of the plugin. Could anyone please check if the plugin does work as expected and let me know?

**Comment by GreyAsteroid** [comment]
> Thanks @GreyAsteroid for providing your API token. I was able to implement some basic commands. But I was not really able to test them as I did not want to change anything on your device.
> 
> I have created a [pre-release version](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v2.2.0-next.1) of the plugin. Could anyone please check if the plugin does work as expected and let me know?

Thanks for your work on this! I went ahead and got the pre-release version running and it seems the device shows up properly and can be turned on and off perfectly. The volume slider accessory is also working great. The only issue I've noticed is that input switching seems to be borked. 

`[smartthings-tv] [Samsung Soundbar Q70T] Error when executing setInputSource of capability samsungvd.audioInputSource: Request failed with status code 422: {"requestId":"6417037913242335142","error":{"code":"ConstraintViolationError","message":"The request is malformed.","details":[{"code":"NotValidValue","target":"commands[0].Command(component=main, capability=samsungvd.audioInputSource, command=setInputSource, commandId=null, arguments=[bluetooth])","message":"setInputSource is not a valid value.","details":[]}]}}`

In case you'll find it helpful I've exported and attached the device attributes and commands.
[Device Attributes.csv](https://github.com/user-attachments/files/16636902/Device.Attributes.csv)
[Device Commands.csv](https://github.com/user-attachments/files/16636904/Device.Commands.csv)

And regarding changes to the device, I currently have it in an empty guest room so any changes won't bother me.

**Comment by MrNoooooooob** [comment]
Hello, is it possible to change the icon into a box so that you can distinguish it.

**Comment by o-lukas** [comment]
@GreyAsteroid I just had a look at changing input sources and it should work as expected now. Thanks again for your API token. I did create a new ["real" release](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v2.2.0) as I screwed things up with pre-releases. Please let me know if everything works as expected now!

**Comment by o-lukas** [comment]
@MrNoooooooob I (probably) found a way to deal with this as well. Soundbars are now published as set top boxes and therefore should have another icon as TVs. I also added a [config property](https://github.com/o-lukas/homebridge-smartthings-tv?tab=readme-ov-file#category) so you can select the icon you want to have for each device. Changes have been released as [v2.3.0](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v2.3.0).
