### ISSUE TITLE
Capability Media Input Source

### ISSUE THREAD

**Issue by anthouny** [o-lukas/homebridge-smartthings-tv#404]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

Hello,

Sorry my English is not good, I don't understand what it is"Capability Media Input Source might not work as expected because it's status is: proposed"

Thank you for the help

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment]
It's just a general warning that the functionality for changing input sources might not work because Samsung noted it as a proposed new feature.

In most cases everything should work as expected. But as long as you don't have any problems you can ignore the warning.
