### ISSUE TITLE
What does status proposed mean?

### ISSUE THREAD

**Issue by Fr3d3rick83** [o-lukas/homebridge-smartthings-tv#409]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

Hi, I´m using you plugin but I dont see the controlls in my Home app on my phone, I just see the volume, but I can see the device at Homebridge devices.

### Logs

[smartthings-tv] [[TV] Samsung Q60 Series (55)] Capability Media Input Source might not work as expected because it's status is: proposed

### Environment Information

```markdown
- Plugin Version: v2.3.1 
- Homebridge Version: latest
- Node.js version: latest
- NPM version: latest
- Operating System: Docker
```

**Comment by o-lukas** [comment]
Please have a look at #371 and #404. You should find solutions/answers to your problems.
