### ISSUE TITLE
Missinf Country

### ISSUE THREAD

**Issue by umutaydin** [o-lukas/homebridge-smartthings-tv#416]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe the bug

There is a missing country (Turkey) in configuration.

### To Reproduce

New account register

### Expected behavior

Having Turkey?

### Logs

N/A

### Logs

N/A

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment]
I think you are referring to the creation of the SmartThings account. I do not have any influence on that. So sadly I can not help you. Please try to contact SmartThings for that issue.
