### ISSUE TITLE
Samsung freestyle projector

### ISSUE THREAD

**Issue by ballance1032** [o-lukas/homebridge-smartthings-tv#430]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

Hi is the Samsung freestyle projector supported? It won’t appear at all in HomeKit. Says in the logs 0 accessories. Thanks for fixing the node issue

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment]
Currently these device types are not supported. I added new configuration properties so supported device types can be configured, so you can add the yourself.

Please check the [README](https://github.com/o-lukas/homebridge-smartthings-tv?tab=readme-ov-file#device-does-not-get-registered) for details.
